// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 487736343;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__parse_workspace_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_workspace",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_root_path = <String>::sse_decode(&mut deserializer);
            let api_entry_file_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::parse_workspace(
                        api_root_path,
                        api_entry_file_path,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RustLedgerDiagnostic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RustLedgerDiagnostic>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RustLedgerDirective> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RustLedgerDirective>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RustPosting> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RustPosting>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::RustAmount> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::RustAmount>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::RustTransactionFlag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::RustTransactionFlag>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::RustAmount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_value = <f64>::sse_decode(deserializer);
        let mut var_commodity = <String>::sse_decode(deserializer);
        let mut var_fractionDigits = <i32>::sse_decode(deserializer);
        return crate::api::RustAmount {
            value: var_value,
            commodity: var_commodity,
            fraction_digits: var_fractionDigits,
        };
    }
}

impl SseDecode for crate::api::RustLedgerDiagnostic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_location = <String>::sse_decode(deserializer);
        let mut var_blocking = <bool>::sse_decode(deserializer);
        return crate::api::RustLedgerDiagnostic {
            message: var_message,
            location: var_location,
            blocking: var_blocking,
        };
    }
}

impl SseDecode for crate::api::RustLedgerDirective {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::RustLedgerDirectiveKind>::sse_decode(deserializer);
        let mut var_dateIso8601 = <String>::sse_decode(deserializer);
        let mut var_sourceLocation = <String>::sse_decode(deserializer);
        let mut var_account = <Option<String>>::sse_decode(deserializer);
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_baseCommodity = <Option<String>>::sse_decode(deserializer);
        let mut var_quoteCommodity = <Option<String>>::sse_decode(deserializer);
        let mut var_amount = <Option<crate::api::RustAmount>>::sse_decode(deserializer);
        let mut var_transactionFlag =
            <Option<crate::api::RustTransactionFlag>>::sse_decode(deserializer);
        let mut var_postings = <Vec<crate::api::RustPosting>>::sse_decode(deserializer);
        return crate::api::RustLedgerDirective {
            kind: var_kind,
            date_iso8601: var_dateIso8601,
            source_location: var_sourceLocation,
            account: var_account,
            title: var_title,
            base_commodity: var_baseCommodity,
            quote_commodity: var_quoteCommodity,
            amount: var_amount,
            transaction_flag: var_transactionFlag,
            postings: var_postings,
        };
    }
}

impl SseDecode for crate::api::RustLedgerDirectiveKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::RustLedgerDirectiveKind::Transaction,
            1 => crate::api::RustLedgerDirectiveKind::Open,
            2 => crate::api::RustLedgerDirectiveKind::Close,
            3 => crate::api::RustLedgerDirectiveKind::Price,
            4 => crate::api::RustLedgerDirectiveKind::Balance,
            _ => unreachable!("Invalid variant for RustLedgerDirectiveKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::RustLedgerSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_workspaceId = <String>::sse_decode(deserializer);
        let mut var_workspaceName = <String>::sse_decode(deserializer);
        let mut var_loadedFileCount = <i32>::sse_decode(deserializer);
        let mut var_directives = <Vec<crate::api::RustLedgerDirective>>::sse_decode(deserializer);
        let mut var_diagnostics = <Vec<crate::api::RustLedgerDiagnostic>>::sse_decode(deserializer);
        return crate::api::RustLedgerSnapshot {
            workspace_id: var_workspaceId,
            workspace_name: var_workspaceName,
            loaded_file_count: var_loadedFileCount,
            directives: var_directives,
            diagnostics: var_diagnostics,
        };
    }
}

impl SseDecode for crate::api::RustPosting {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_account = <String>::sse_decode(deserializer);
        let mut var_amount = <Option<crate::api::RustAmount>>::sse_decode(deserializer);
        return crate::api::RustPosting {
            account: var_account,
            amount: var_amount,
        };
    }
}

impl SseDecode for crate::api::RustTransactionFlag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::RustTransactionFlag::Cleared,
            1 => crate::api::RustTransactionFlag::Pending,
            _ => unreachable!("Invalid variant for RustTransactionFlag: {}", inner),
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__parse_workspace_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustAmount {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.value.into_into_dart().into_dart(),
            self.commodity.into_into_dart().into_dart(),
            self.fraction_digits.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::RustAmount {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustAmount> for crate::api::RustAmount {
    fn into_into_dart(self) -> crate::api::RustAmount {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustLedgerDiagnostic {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.message.into_into_dart().into_dart(),
            self.location.into_into_dart().into_dart(),
            self.blocking.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RustLedgerDiagnostic
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustLedgerDiagnostic>
    for crate::api::RustLedgerDiagnostic
{
    fn into_into_dart(self) -> crate::api::RustLedgerDiagnostic {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustLedgerDirective {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.date_iso8601.into_into_dart().into_dart(),
            self.source_location.into_into_dart().into_dart(),
            self.account.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.base_commodity.into_into_dart().into_dart(),
            self.quote_commodity.into_into_dart().into_dart(),
            self.amount.into_into_dart().into_dart(),
            self.transaction_flag.into_into_dart().into_dart(),
            self.postings.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RustLedgerDirective
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustLedgerDirective>
    for crate::api::RustLedgerDirective
{
    fn into_into_dart(self) -> crate::api::RustLedgerDirective {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustLedgerDirectiveKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Transaction => 0.into_dart(),
            Self::Open => 1.into_dart(),
            Self::Close => 2.into_dart(),
            Self::Price => 3.into_dart(),
            Self::Balance => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RustLedgerDirectiveKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustLedgerDirectiveKind>
    for crate::api::RustLedgerDirectiveKind
{
    fn into_into_dart(self) -> crate::api::RustLedgerDirectiveKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustLedgerSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.workspace_id.into_into_dart().into_dart(),
            self.workspace_name.into_into_dart().into_dart(),
            self.loaded_file_count.into_into_dart().into_dart(),
            self.directives.into_into_dart().into_dart(),
            self.diagnostics.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RustLedgerSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustLedgerSnapshot>
    for crate::api::RustLedgerSnapshot
{
    fn into_into_dart(self) -> crate::api::RustLedgerSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustPosting {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.account.into_into_dart().into_dart(),
            self.amount.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::RustPosting {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustPosting> for crate::api::RustPosting {
    fn into_into_dart(self) -> crate::api::RustPosting {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RustTransactionFlag {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Cleared => 0.into_dart(),
            Self::Pending => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RustTransactionFlag
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RustTransactionFlag>
    for crate::api::RustTransactionFlag
{
    fn into_into_dart(self) -> crate::api::RustTransactionFlag {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RustLedgerDiagnostic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RustLedgerDiagnostic>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RustLedgerDirective> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RustLedgerDirective>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RustPosting> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RustPosting>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::RustAmount> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::RustAmount>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::RustTransactionFlag> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::RustTransactionFlag>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::RustAmount {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.value, serializer);
        <String>::sse_encode(self.commodity, serializer);
        <i32>::sse_encode(self.fraction_digits, serializer);
    }
}

impl SseEncode for crate::api::RustLedgerDiagnostic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.message, serializer);
        <String>::sse_encode(self.location, serializer);
        <bool>::sse_encode(self.blocking, serializer);
    }
}

impl SseEncode for crate::api::RustLedgerDirective {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::RustLedgerDirectiveKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.date_iso8601, serializer);
        <String>::sse_encode(self.source_location, serializer);
        <Option<String>>::sse_encode(self.account, serializer);
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.base_commodity, serializer);
        <Option<String>>::sse_encode(self.quote_commodity, serializer);
        <Option<crate::api::RustAmount>>::sse_encode(self.amount, serializer);
        <Option<crate::api::RustTransactionFlag>>::sse_encode(self.transaction_flag, serializer);
        <Vec<crate::api::RustPosting>>::sse_encode(self.postings, serializer);
    }
}

impl SseEncode for crate::api::RustLedgerDirectiveKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::RustLedgerDirectiveKind::Transaction => 0,
                crate::api::RustLedgerDirectiveKind::Open => 1,
                crate::api::RustLedgerDirectiveKind::Close => 2,
                crate::api::RustLedgerDirectiveKind::Price => 3,
                crate::api::RustLedgerDirectiveKind::Balance => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::RustLedgerSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.workspace_id, serializer);
        <String>::sse_encode(self.workspace_name, serializer);
        <i32>::sse_encode(self.loaded_file_count, serializer);
        <Vec<crate::api::RustLedgerDirective>>::sse_encode(self.directives, serializer);
        <Vec<crate::api::RustLedgerDiagnostic>>::sse_encode(self.diagnostics, serializer);
    }
}

impl SseEncode for crate::api::RustPosting {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.account, serializer);
        <Option<crate::api::RustAmount>>::sse_encode(self.amount, serializer);
    }
}

impl SseEncode for crate::api::RustTransactionFlag {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::RustTransactionFlag::Cleared => 0,
                crate::api::RustTransactionFlag::Pending => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
