name: beancount_data
description: Data implementations for Tally Bean.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  beancount_domain:
    path: ../beancount_domain
  ledger_io:
    path: ../ledger_io
  beancount_bridge:
    path: ../beancount_bridge

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
