// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustLedgerSnapshot> parseWorkspace({
  required String rootPath,
  required String entryFilePath,
}) => RustLib.instance.api.crateApiParseWorkspace(
  rootPath: rootPath,
  entryFilePath: entryFilePath,
);

class RustAmount {
  final double value;
  final String commodity;
  final int fractionDigits;

  const RustAmount({
    required this.value,
    required this.commodity,
    required this.fractionDigits,
  });

  @override
  int get hashCode =>
      value.hashCode ^ commodity.hashCode ^ fractionDigits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAmount &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          commodity == other.commodity &&
          fractionDigits == other.fractionDigits;
}

class RustLedgerDiagnostic {
  final String message;
  final String location;
  final bool blocking;

  const RustLedgerDiagnostic({
    required this.message,
    required this.location,
    required this.blocking,
  });

  @override
  int get hashCode => message.hashCode ^ location.hashCode ^ blocking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerDiagnostic &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          location == other.location &&
          blocking == other.blocking;
}

class RustLedgerDirective {
  final RustLedgerDirectiveKind kind;
  final String dateIso8601;
  final String sourceLocation;
  final String? account;
  final String? title;
  final String? baseCommodity;
  final String? quoteCommodity;
  final RustAmount? amount;
  final RustTransactionFlag? transactionFlag;
  final List<RustPosting> postings;

  const RustLedgerDirective({
    required this.kind,
    required this.dateIso8601,
    required this.sourceLocation,
    this.account,
    this.title,
    this.baseCommodity,
    this.quoteCommodity,
    this.amount,
    this.transactionFlag,
    required this.postings,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      dateIso8601.hashCode ^
      sourceLocation.hashCode ^
      account.hashCode ^
      title.hashCode ^
      baseCommodity.hashCode ^
      quoteCommodity.hashCode ^
      amount.hashCode ^
      transactionFlag.hashCode ^
      postings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerDirective &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          dateIso8601 == other.dateIso8601 &&
          sourceLocation == other.sourceLocation &&
          account == other.account &&
          title == other.title &&
          baseCommodity == other.baseCommodity &&
          quoteCommodity == other.quoteCommodity &&
          amount == other.amount &&
          transactionFlag == other.transactionFlag &&
          postings == other.postings;
}

enum RustLedgerDirectiveKind { transaction, open, close, price, balance }

class RustLedgerSnapshot {
  final String workspaceId;
  final String workspaceName;
  final int loadedFileCount;
  final List<RustLedgerDirective> directives;
  final List<RustLedgerDiagnostic> diagnostics;

  const RustLedgerSnapshot({
    required this.workspaceId,
    required this.workspaceName,
    required this.loadedFileCount,
    required this.directives,
    required this.diagnostics,
  });

  @override
  int get hashCode =>
      workspaceId.hashCode ^
      workspaceName.hashCode ^
      loadedFileCount.hashCode ^
      directives.hashCode ^
      diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerSnapshot &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          workspaceName == other.workspaceName &&
          loadedFileCount == other.loadedFileCount &&
          directives == other.directives &&
          diagnostics == other.diagnostics;
}

class RustPosting {
  final String account;
  final RustAmount? amount;

  const RustPosting({required this.account, this.amount});

  @override
  int get hashCode => account.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPosting &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          amount == other.amount;
}

enum RustTransactionFlag { cleared, pending }
