// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 487736343;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'beancount_bridge_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<RustLedgerSnapshot> crateApiParseWorkspace({
    required String rootPath,
    required String entryFilePath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<RustLedgerSnapshot> crateApiParseWorkspace({
    required String rootPath,
    required String entryFilePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(entryFilePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_ledger_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseWorkspaceConstMeta,
        argValues: [rootPath, entryFilePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseWorkspaceConstMeta => const TaskConstMeta(
    debugName: "parse_workspace",
    argNames: ["rootPath", "entryFilePath"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RustAmount dco_decode_box_autoadd_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_amount(raw);
  }

  @protected
  RustTransactionFlag dco_decode_box_autoadd_rust_transaction_flag(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_transaction_flag(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustLedgerDiagnostic> dco_decode_list_rust_ledger_diagnostic(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_ledger_diagnostic)
        .toList();
  }

  @protected
  List<RustLedgerDirective> dco_decode_list_rust_ledger_directive(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_ledger_directive)
        .toList();
  }

  @protected
  List<RustPosting> dco_decode_list_rust_posting(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_posting).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RustAmount? dco_decode_opt_box_autoadd_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rust_amount(raw);
  }

  @protected
  RustTransactionFlag? dco_decode_opt_box_autoadd_rust_transaction_flag(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_rust_transaction_flag(raw);
  }

  @protected
  RustAmount dco_decode_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustAmount(
      value: dco_decode_f_64(arr[0]),
      commodity: dco_decode_String(arr[1]),
      fractionDigits: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  RustLedgerDiagnostic dco_decode_rust_ledger_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustLedgerDiagnostic(
      message: dco_decode_String(arr[0]),
      location: dco_decode_String(arr[1]),
      blocking: dco_decode_bool(arr[2]),
    );
  }

  @protected
  RustLedgerDirective dco_decode_rust_ledger_directive(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RustLedgerDirective(
      kind: dco_decode_rust_ledger_directive_kind(arr[0]),
      dateIso8601: dco_decode_String(arr[1]),
      sourceLocation: dco_decode_String(arr[2]),
      account: dco_decode_opt_String(arr[3]),
      title: dco_decode_opt_String(arr[4]),
      baseCommodity: dco_decode_opt_String(arr[5]),
      quoteCommodity: dco_decode_opt_String(arr[6]),
      amount: dco_decode_opt_box_autoadd_rust_amount(arr[7]),
      transactionFlag: dco_decode_opt_box_autoadd_rust_transaction_flag(arr[8]),
      postings: dco_decode_list_rust_posting(arr[9]),
    );
  }

  @protected
  RustLedgerDirectiveKind dco_decode_rust_ledger_directive_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustLedgerDirectiveKind.values[raw as int];
  }

  @protected
  RustLedgerSnapshot dco_decode_rust_ledger_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustLedgerSnapshot(
      workspaceId: dco_decode_String(arr[0]),
      workspaceName: dco_decode_String(arr[1]),
      loadedFileCount: dco_decode_i_32(arr[2]),
      directives: dco_decode_list_rust_ledger_directive(arr[3]),
      diagnostics: dco_decode_list_rust_ledger_diagnostic(arr[4]),
    );
  }

  @protected
  RustPosting dco_decode_rust_posting(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustPosting(
      account: dco_decode_String(arr[0]),
      amount: dco_decode_opt_box_autoadd_rust_amount(arr[1]),
    );
  }

  @protected
  RustTransactionFlag dco_decode_rust_transaction_flag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustTransactionFlag.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RustAmount sse_decode_box_autoadd_rust_amount(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_amount(deserializer));
  }

  @protected
  RustTransactionFlag sse_decode_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_transaction_flag(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustLedgerDiagnostic> sse_decode_list_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustLedgerDiagnostic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_ledger_diagnostic(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustLedgerDirective> sse_decode_list_rust_ledger_directive(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustLedgerDirective>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_ledger_directive(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustPosting> sse_decode_list_rust_posting(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustPosting>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_posting(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAmount? sse_decode_opt_box_autoadd_rust_amount(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_amount(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustTransactionFlag? sse_decode_opt_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_transaction_flag(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAmount sse_decode_rust_amount(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_f_64(deserializer);
    var var_commodity = sse_decode_String(deserializer);
    var var_fractionDigits = sse_decode_i_32(deserializer);
    return RustAmount(
      value: var_value,
      commodity: var_commodity,
      fractionDigits: var_fractionDigits,
    );
  }

  @protected
  RustLedgerDiagnostic sse_decode_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_blocking = sse_decode_bool(deserializer);
    return RustLedgerDiagnostic(
      message: var_message,
      location: var_location,
      blocking: var_blocking,
    );
  }

  @protected
  RustLedgerDirective sse_decode_rust_ledger_directive(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_rust_ledger_directive_kind(deserializer);
    var var_dateIso8601 = sse_decode_String(deserializer);
    var var_sourceLocation = sse_decode_String(deserializer);
    var var_account = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_baseCommodity = sse_decode_opt_String(deserializer);
    var var_quoteCommodity = sse_decode_opt_String(deserializer);
    var var_amount = sse_decode_opt_box_autoadd_rust_amount(deserializer);
    var var_transactionFlag = sse_decode_opt_box_autoadd_rust_transaction_flag(
      deserializer,
    );
    var var_postings = sse_decode_list_rust_posting(deserializer);
    return RustLedgerDirective(
      kind: var_kind,
      dateIso8601: var_dateIso8601,
      sourceLocation: var_sourceLocation,
      account: var_account,
      title: var_title,
      baseCommodity: var_baseCommodity,
      quoteCommodity: var_quoteCommodity,
      amount: var_amount,
      transactionFlag: var_transactionFlag,
      postings: var_postings,
    );
  }

  @protected
  RustLedgerDirectiveKind sse_decode_rust_ledger_directive_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RustLedgerDirectiveKind.values[inner];
  }

  @protected
  RustLedgerSnapshot sse_decode_rust_ledger_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workspaceId = sse_decode_String(deserializer);
    var var_workspaceName = sse_decode_String(deserializer);
    var var_loadedFileCount = sse_decode_i_32(deserializer);
    var var_directives = sse_decode_list_rust_ledger_directive(deserializer);
    var var_diagnostics = sse_decode_list_rust_ledger_diagnostic(deserializer);
    return RustLedgerSnapshot(
      workspaceId: var_workspaceId,
      workspaceName: var_workspaceName,
      loadedFileCount: var_loadedFileCount,
      directives: var_directives,
      diagnostics: var_diagnostics,
    );
  }

  @protected
  RustPosting sse_decode_rust_posting(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_String(deserializer);
    var var_amount = sse_decode_opt_box_autoadd_rust_amount(deserializer);
    return RustPosting(account: var_account, amount: var_amount);
  }

  @protected
  RustTransactionFlag sse_decode_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RustTransactionFlag.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_rust_amount(
    RustAmount self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_amount(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_transaction_flag(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_ledger_diagnostic(
    List<RustLedgerDiagnostic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_ledger_diagnostic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_ledger_directive(
    List<RustLedgerDirective> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_ledger_directive(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_posting(
    List<RustPosting> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_posting(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_amount(
    RustAmount? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_amount(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_transaction_flag(
    RustTransactionFlag? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_transaction_flag(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_amount(RustAmount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.value, serializer);
    sse_encode_String(self.commodity, serializer);
    sse_encode_i_32(self.fractionDigits, serializer);
  }

  @protected
  void sse_encode_rust_ledger_diagnostic(
    RustLedgerDiagnostic self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_bool(self.blocking, serializer);
  }

  @protected
  void sse_encode_rust_ledger_directive(
    RustLedgerDirective self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_ledger_directive_kind(self.kind, serializer);
    sse_encode_String(self.dateIso8601, serializer);
    sse_encode_String(self.sourceLocation, serializer);
    sse_encode_opt_String(self.account, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.baseCommodity, serializer);
    sse_encode_opt_String(self.quoteCommodity, serializer);
    sse_encode_opt_box_autoadd_rust_amount(self.amount, serializer);
    sse_encode_opt_box_autoadd_rust_transaction_flag(
      self.transactionFlag,
      serializer,
    );
    sse_encode_list_rust_posting(self.postings, serializer);
  }

  @protected
  void sse_encode_rust_ledger_directive_kind(
    RustLedgerDirectiveKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_rust_ledger_snapshot(
    RustLedgerSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.workspaceId, serializer);
    sse_encode_String(self.workspaceName, serializer);
    sse_encode_i_32(self.loadedFileCount, serializer);
    sse_encode_list_rust_ledger_directive(self.directives, serializer);
    sse_encode_list_rust_ledger_diagnostic(self.diagnostics, serializer);
  }

  @protected
  void sse_encode_rust_posting(RustPosting self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.account, serializer);
    sse_encode_opt_box_autoadd_rust_amount(self.amount, serializer);
  }

  @protected
  void sse_encode_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
