// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustLedgerSnapshot> parseWorkspace({
  required String rootPath,
  required String entryFilePath,
}) => RustLib.instance.api.crateApiParseWorkspace(
  rootPath: rootPath,
  entryFilePath: entryFilePath,
);

Future<PlatformInt64> openWorkspace({
  required String rootPath,
  required String entryFilePath,
}) => RustLib.instance.api.crateApiOpenWorkspace(
  rootPath: rootPath,
  entryFilePath: entryFilePath,
);

Future<void> closeWorkspace({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiCloseWorkspace(handle: handle);

Future<RustRefreshResult> refreshWorkspace({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiRefreshWorkspace(handle: handle);

Future<RustWorkspaceSummary> getWorkspaceSummary({
  required PlatformInt64 handle,
}) => RustLib.instance.api.crateApiGetWorkspaceSummary(handle: handle);

Future<List<RustLedgerDiagnostic>> listDiagnostics({
  required PlatformInt64 handle,
  required RustDiagnosticQuery query,
}) =>
    RustLib.instance.api.crateApiListDiagnostics(handle: handle, query: query);

Future<RustJournalPage> getJournalPage({
  required PlatformInt64 handle,
  required RustJournalQuery query,
}) => RustLib.instance.api.crateApiGetJournalPage(handle: handle, query: query);

Future<RustAccountTree> getAccountTree({
  required PlatformInt64 handle,
  required RustAccountTreeQuery query,
}) => RustLib.instance.api.crateApiGetAccountTree(handle: handle, query: query);

Future<RustReportSnapshot> getReportSnapshot({
  required PlatformInt64 handle,
  required RustReportQuery query,
}) => RustLib.instance.api.crateApiGetReportSnapshot(
  handle: handle,
  query: query,
);

Future<List<RustDocumentSummary>> listDocuments({
  required PlatformInt64 handle,
}) => RustLib.instance.api.crateApiListDocuments(handle: handle);

Future<RustDocument> getDocument({
  required PlatformInt64 handle,
  required String documentId,
}) => RustLib.instance.api.crateApiGetDocument(
  handle: handle,
  documentId: documentId,
);

class RustAccountNode {
  final String name;
  final String subtitle;
  final String balance;
  final bool isClosed;
  final List<RustAccountNode> children;

  const RustAccountNode({
    required this.name,
    required this.subtitle,
    required this.balance,
    required this.isClosed,
    required this.children,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      subtitle.hashCode ^
      balance.hashCode ^
      isClosed.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAccountNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          subtitle == other.subtitle &&
          balance == other.balance &&
          isClosed == other.isClosed &&
          children == other.children;
}

class RustAccountTree {
  final List<RustAccountNode> nodes;

  const RustAccountTree({required this.nodes});

  @override
  int get hashCode => nodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAccountTree &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes;
}

class RustAccountTreeQuery {
  final bool includeClosedAccounts;

  const RustAccountTreeQuery({required this.includeClosedAccounts});

  @override
  int get hashCode => includeClosedAccounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAccountTreeQuery &&
          runtimeType == other.runtimeType &&
          includeClosedAccounts == other.includeClosedAccounts;
}

class RustAmount {
  final double value;
  final String commodity;
  final int fractionDigits;

  const RustAmount({
    required this.value,
    required this.commodity,
    required this.fractionDigits,
  });

  @override
  int get hashCode =>
      value.hashCode ^ commodity.hashCode ^ fractionDigits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAmount &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          commodity == other.commodity &&
          fractionDigits == other.fractionDigits;
}

class RustDiagnosticQuery {
  final bool includeBlocking;
  final bool includeNonBlocking;

  const RustDiagnosticQuery({
    required this.includeBlocking,
    required this.includeNonBlocking,
  });

  @override
  int get hashCode => includeBlocking.hashCode ^ includeNonBlocking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDiagnosticQuery &&
          runtimeType == other.runtimeType &&
          includeBlocking == other.includeBlocking &&
          includeNonBlocking == other.includeNonBlocking;
}

class RustDocument {
  final String documentId;
  final String fileName;
  final String relativePath;
  final String content;
  final int sizeBytes;
  final bool isEntry;

  const RustDocument({
    required this.documentId,
    required this.fileName,
    required this.relativePath,
    required this.content,
    required this.sizeBytes,
    required this.isEntry,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      fileName.hashCode ^
      relativePath.hashCode ^
      content.hashCode ^
      sizeBytes.hashCode ^
      isEntry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDocument &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          fileName == other.fileName &&
          relativePath == other.relativePath &&
          content == other.content &&
          sizeBytes == other.sizeBytes &&
          isEntry == other.isEntry;
}

class RustDocumentSummary {
  final String documentId;
  final String fileName;
  final String relativePath;
  final int sizeBytes;
  final bool isEntry;

  const RustDocumentSummary({
    required this.documentId,
    required this.fileName,
    required this.relativePath,
    required this.sizeBytes,
    required this.isEntry,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      fileName.hashCode ^
      relativePath.hashCode ^
      sizeBytes.hashCode ^
      isEntry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDocumentSummary &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          fileName == other.fileName &&
          relativePath == other.relativePath &&
          sizeBytes == other.sizeBytes &&
          isEntry == other.isEntry;
}

class RustJournalEntry {
  final String dateIso8601;
  final RustJournalEntryType entryType;
  final String title;
  final String primaryAccount;
  final String? secondaryAccount;
  final String? detail;
  final RustAmount? amount;
  final String? status;
  final RustTransactionFlag? transactionFlag;

  const RustJournalEntry({
    required this.dateIso8601,
    required this.entryType,
    required this.title,
    required this.primaryAccount,
    this.secondaryAccount,
    this.detail,
    this.amount,
    this.status,
    this.transactionFlag,
  });

  @override
  int get hashCode =>
      dateIso8601.hashCode ^
      entryType.hashCode ^
      title.hashCode ^
      primaryAccount.hashCode ^
      secondaryAccount.hashCode ^
      detail.hashCode ^
      amount.hashCode ^
      status.hashCode ^
      transactionFlag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustJournalEntry &&
          runtimeType == other.runtimeType &&
          dateIso8601 == other.dateIso8601 &&
          entryType == other.entryType &&
          title == other.title &&
          primaryAccount == other.primaryAccount &&
          secondaryAccount == other.secondaryAccount &&
          detail == other.detail &&
          amount == other.amount &&
          status == other.status &&
          transactionFlag == other.transactionFlag;
}

enum RustJournalEntryType { transaction, open, close, price, balance }

class RustJournalPage {
  final int totalCount;
  final List<RustJournalEntry> entries;

  const RustJournalPage({required this.totalCount, required this.entries});

  @override
  int get hashCode => totalCount.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustJournalPage &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          entries == other.entries;
}

class RustJournalQuery {
  final int pageSize;
  final int offset;

  const RustJournalQuery({required this.pageSize, required this.offset});

  @override
  int get hashCode => pageSize.hashCode ^ offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustJournalQuery &&
          runtimeType == other.runtimeType &&
          pageSize == other.pageSize &&
          offset == other.offset;
}

class RustLedgerDiagnostic {
  final String message;
  final String location;
  final bool blocking;

  const RustLedgerDiagnostic({
    required this.message,
    required this.location,
    required this.blocking,
  });

  @override
  int get hashCode => message.hashCode ^ location.hashCode ^ blocking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerDiagnostic &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          location == other.location &&
          blocking == other.blocking;
}

class RustLedgerDirective {
  final RustLedgerDirectiveKind kind;
  final String dateIso8601;
  final String sourceLocation;
  final String? account;
  final String? title;
  final String? baseCommodity;
  final String? quoteCommodity;
  final RustAmount? amount;
  final RustTransactionFlag? transactionFlag;
  final List<RustPosting> postings;

  const RustLedgerDirective({
    required this.kind,
    required this.dateIso8601,
    required this.sourceLocation,
    this.account,
    this.title,
    this.baseCommodity,
    this.quoteCommodity,
    this.amount,
    this.transactionFlag,
    required this.postings,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      dateIso8601.hashCode ^
      sourceLocation.hashCode ^
      account.hashCode ^
      title.hashCode ^
      baseCommodity.hashCode ^
      quoteCommodity.hashCode ^
      amount.hashCode ^
      transactionFlag.hashCode ^
      postings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerDirective &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          dateIso8601 == other.dateIso8601 &&
          sourceLocation == other.sourceLocation &&
          account == other.account &&
          title == other.title &&
          baseCommodity == other.baseCommodity &&
          quoteCommodity == other.quoteCommodity &&
          amount == other.amount &&
          transactionFlag == other.transactionFlag &&
          postings == other.postings;
}

enum RustLedgerDirectiveKind { transaction, open, close, price, balance }

class RustLedgerSnapshot {
  final String workspaceId;
  final String workspaceName;
  final int loadedFileCount;
  final List<RustLedgerDirective> directives;
  final List<RustLedgerDiagnostic> diagnostics;

  const RustLedgerSnapshot({
    required this.workspaceId,
    required this.workspaceName,
    required this.loadedFileCount,
    required this.directives,
    required this.diagnostics,
  });

  @override
  int get hashCode =>
      workspaceId.hashCode ^
      workspaceName.hashCode ^
      loadedFileCount.hashCode ^
      directives.hashCode ^
      diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLedgerSnapshot &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          workspaceName == other.workspaceName &&
          loadedFileCount == other.loadedFileCount &&
          directives == other.directives &&
          diagnostics == other.diagnostics;
}

class RustPosting {
  final String account;
  final RustAmount? amount;

  const RustPosting({required this.account, this.amount});

  @override
  int get hashCode => account.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPosting &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          amount == other.amount;
}

class RustRefreshResult {
  final RustWorkspaceSummary summary;
  final int diagnosticsCount;

  const RustRefreshResult({
    required this.summary,
    required this.diagnosticsCount,
  });

  @override
  int get hashCode => summary.hashCode ^ diagnosticsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRefreshResult &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          diagnosticsCount == other.diagnosticsCount;
}

class RustReportQuery {
  const RustReportQuery();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustReportQuery && runtimeType == other.runtimeType;
}

class RustReportResult {
  final String key;
  final List<String> lines;

  const RustReportResult({required this.key, required this.lines});

  @override
  int get hashCode => key.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustReportResult &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          lines == other.lines;
}

class RustReportSnapshot {
  final List<RustReportResult> results;

  const RustReportSnapshot({required this.results});

  @override
  int get hashCode => results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustReportSnapshot &&
          runtimeType == other.runtimeType &&
          results == other.results;
}

enum RustTransactionFlag { cleared, pending }

class RustTrendSummary {
  final String chartLabel;
  final double income;
  final double expense;
  final double balance;

  const RustTrendSummary({
    required this.chartLabel,
    required this.income,
    required this.expense,
    required this.balance,
  });

  @override
  int get hashCode =>
      chartLabel.hashCode ^
      income.hashCode ^
      expense.hashCode ^
      balance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTrendSummary &&
          runtimeType == other.runtimeType &&
          chartLabel == other.chartLabel &&
          income == other.income &&
          expense == other.expense &&
          balance == other.balance;
}

class RustWorkspaceSummary {
  final String workspaceId;
  final String workspaceName;
  final int loadedFileCount;
  final int openAccountCount;
  final int closedAccountCount;
  final String netWorth;
  final String totalAssets;
  final String totalLiabilities;
  final String changeDescription;
  final RustTrendSummary weekTrend;
  final RustTrendSummary monthTrend;

  const RustWorkspaceSummary({
    required this.workspaceId,
    required this.workspaceName,
    required this.loadedFileCount,
    required this.openAccountCount,
    required this.closedAccountCount,
    required this.netWorth,
    required this.totalAssets,
    required this.totalLiabilities,
    required this.changeDescription,
    required this.weekTrend,
    required this.monthTrend,
  });

  @override
  int get hashCode =>
      workspaceId.hashCode ^
      workspaceName.hashCode ^
      loadedFileCount.hashCode ^
      openAccountCount.hashCode ^
      closedAccountCount.hashCode ^
      netWorth.hashCode ^
      totalAssets.hashCode ^
      totalLiabilities.hashCode ^
      changeDescription.hashCode ^
      weekTrend.hashCode ^
      monthTrend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustWorkspaceSummary &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          workspaceName == other.workspaceName &&
          loadedFileCount == other.loadedFileCount &&
          openAccountCount == other.openAccountCount &&
          closedAccountCount == other.closedAccountCount &&
          netWorth == other.netWorth &&
          totalAssets == other.totalAssets &&
          totalLiabilities == other.totalLiabilities &&
          changeDescription == other.changeDescription &&
          weekTrend == other.weekTrend &&
          monthTrend == other.monthTrend;
}
