// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  RustAccountTreeQuery dco_decode_box_autoadd_rust_account_tree_query(
    dynamic raw,
  );

  @protected
  RustAmount dco_decode_box_autoadd_rust_amount(dynamic raw);

  @protected
  RustDiagnosticQuery dco_decode_box_autoadd_rust_diagnostic_query(dynamic raw);

  @protected
  RustJournalQuery dco_decode_box_autoadd_rust_journal_query(dynamic raw);

  @protected
  RustReportQuery dco_decode_box_autoadd_rust_report_query(dynamic raw);

  @protected
  RustTransactionFlag dco_decode_box_autoadd_rust_transaction_flag(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RustAccountNode> dco_decode_list_rust_account_node(dynamic raw);

  @protected
  List<RustDocumentSummary> dco_decode_list_rust_document_summary(dynamic raw);

  @protected
  List<RustJournalEntry> dco_decode_list_rust_journal_entry(dynamic raw);

  @protected
  List<RustLedgerDiagnostic> dco_decode_list_rust_ledger_diagnostic(
    dynamic raw,
  );

  @protected
  List<RustReportResult> dco_decode_list_rust_report_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RustAmount? dco_decode_opt_box_autoadd_rust_amount(dynamic raw);

  @protected
  RustTransactionFlag? dco_decode_opt_box_autoadd_rust_transaction_flag(
    dynamic raw,
  );

  @protected
  RustAccountNode dco_decode_rust_account_node(dynamic raw);

  @protected
  RustAccountTree dco_decode_rust_account_tree(dynamic raw);

  @protected
  RustAccountTreeQuery dco_decode_rust_account_tree_query(dynamic raw);

  @protected
  RustAmount dco_decode_rust_amount(dynamic raw);

  @protected
  RustDiagnosticQuery dco_decode_rust_diagnostic_query(dynamic raw);

  @protected
  RustDocument dco_decode_rust_document(dynamic raw);

  @protected
  RustDocumentSummary dco_decode_rust_document_summary(dynamic raw);

  @protected
  RustJournalEntry dco_decode_rust_journal_entry(dynamic raw);

  @protected
  RustJournalEntryType dco_decode_rust_journal_entry_type(dynamic raw);

  @protected
  RustJournalPage dco_decode_rust_journal_page(dynamic raw);

  @protected
  RustJournalQuery dco_decode_rust_journal_query(dynamic raw);

  @protected
  RustLedgerDiagnostic dco_decode_rust_ledger_diagnostic(dynamic raw);

  @protected
  RustLedgerSummary dco_decode_rust_ledger_summary(dynamic raw);

  @protected
  RustRefreshResult dco_decode_rust_refresh_result(dynamic raw);

  @protected
  RustReportQuery dco_decode_rust_report_query(dynamic raw);

  @protected
  RustReportResult dco_decode_rust_report_result(dynamic raw);

  @protected
  RustReportSnapshot dco_decode_rust_report_snapshot(dynamic raw);

  @protected
  RustTransactionFlag dco_decode_rust_transaction_flag(dynamic raw);

  @protected
  RustTrendSummary dco_decode_rust_trend_summary(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  RustAccountTreeQuery sse_decode_box_autoadd_rust_account_tree_query(
    SseDeserializer deserializer,
  );

  @protected
  RustAmount sse_decode_box_autoadd_rust_amount(SseDeserializer deserializer);

  @protected
  RustDiagnosticQuery sse_decode_box_autoadd_rust_diagnostic_query(
    SseDeserializer deserializer,
  );

  @protected
  RustJournalQuery sse_decode_box_autoadd_rust_journal_query(
    SseDeserializer deserializer,
  );

  @protected
  RustReportQuery sse_decode_box_autoadd_rust_report_query(
    SseDeserializer deserializer,
  );

  @protected
  RustTransactionFlag sse_decode_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RustAccountNode> sse_decode_list_rust_account_node(
    SseDeserializer deserializer,
  );

  @protected
  List<RustDocumentSummary> sse_decode_list_rust_document_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<RustJournalEntry> sse_decode_list_rust_journal_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<RustLedgerDiagnostic> sse_decode_list_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  List<RustReportResult> sse_decode_list_rust_report_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RustAmount? sse_decode_opt_box_autoadd_rust_amount(
    SseDeserializer deserializer,
  );

  @protected
  RustTransactionFlag? sse_decode_opt_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  );

  @protected
  RustAccountNode sse_decode_rust_account_node(SseDeserializer deserializer);

  @protected
  RustAccountTree sse_decode_rust_account_tree(SseDeserializer deserializer);

  @protected
  RustAccountTreeQuery sse_decode_rust_account_tree_query(
    SseDeserializer deserializer,
  );

  @protected
  RustAmount sse_decode_rust_amount(SseDeserializer deserializer);

  @protected
  RustDiagnosticQuery sse_decode_rust_diagnostic_query(
    SseDeserializer deserializer,
  );

  @protected
  RustDocument sse_decode_rust_document(SseDeserializer deserializer);

  @protected
  RustDocumentSummary sse_decode_rust_document_summary(
    SseDeserializer deserializer,
  );

  @protected
  RustJournalEntry sse_decode_rust_journal_entry(SseDeserializer deserializer);

  @protected
  RustJournalEntryType sse_decode_rust_journal_entry_type(
    SseDeserializer deserializer,
  );

  @protected
  RustJournalPage sse_decode_rust_journal_page(SseDeserializer deserializer);

  @protected
  RustJournalQuery sse_decode_rust_journal_query(SseDeserializer deserializer);

  @protected
  RustLedgerDiagnostic sse_decode_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  RustLedgerSummary sse_decode_rust_ledger_summary(
    SseDeserializer deserializer,
  );

  @protected
  RustRefreshResult sse_decode_rust_refresh_result(
    SseDeserializer deserializer,
  );

  @protected
  RustReportQuery sse_decode_rust_report_query(SseDeserializer deserializer);

  @protected
  RustReportResult sse_decode_rust_report_result(SseDeserializer deserializer);

  @protected
  RustReportSnapshot sse_decode_rust_report_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  RustTransactionFlag sse_decode_rust_transaction_flag(
    SseDeserializer deserializer,
  );

  @protected
  RustTrendSummary sse_decode_rust_trend_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rust_account_tree_query(
    RustAccountTreeQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_amount(
    RustAmount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_diagnostic_query(
    RustDiagnosticQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_journal_query(
    RustJournalQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_report_query(
    RustReportQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_account_node(
    List<RustAccountNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_document_summary(
    List<RustDocumentSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_journal_entry(
    List<RustJournalEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_ledger_diagnostic(
    List<RustLedgerDiagnostic> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_report_result(
    List<RustReportResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rust_amount(
    RustAmount? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rust_transaction_flag(
    RustTransactionFlag? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_account_node(
    RustAccountNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_account_tree(
    RustAccountTree self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_account_tree_query(
    RustAccountTreeQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_amount(RustAmount self, SseSerializer serializer);

  @protected
  void sse_encode_rust_diagnostic_query(
    RustDiagnosticQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_document(RustDocument self, SseSerializer serializer);

  @protected
  void sse_encode_rust_document_summary(
    RustDocumentSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_journal_entry(
    RustJournalEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_journal_entry_type(
    RustJournalEntryType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_journal_page(
    RustJournalPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_journal_query(
    RustJournalQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ledger_diagnostic(
    RustLedgerDiagnostic self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ledger_summary(
    RustLedgerSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_refresh_result(
    RustRefreshResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_report_query(
    RustReportQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_report_result(
    RustReportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_report_snapshot(
    RustReportSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_trend_summary(
    RustTrendSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
