// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -145272785;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'beancount_bridge_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCloseLedgerSession({required PlatformInt64 handle});

  Future<RustAccountTree> crateApiGetAccountTree({
    required PlatformInt64 handle,
    required RustAccountTreeQuery query,
  });

  Future<RustDocument> crateApiGetDocument({
    required PlatformInt64 handle,
    required String documentId,
  });

  Future<RustJournalPage> crateApiGetJournalPage({
    required PlatformInt64 handle,
    required RustJournalQuery query,
  });

  Future<RustLedgerSummary> crateApiGetLedgerSummary({
    required PlatformInt64 handle,
  });

  Future<RustReportSnapshot> crateApiGetReportSnapshot({
    required PlatformInt64 handle,
    required RustReportQuery query,
  });

  Future<List<RustLedgerDiagnostic>> crateApiListDiagnostics({
    required PlatformInt64 handle,
    required RustDiagnosticQuery query,
  });

  Future<List<RustDocumentSummary>> crateApiListDocuments({
    required PlatformInt64 handle,
  });

  Future<PlatformInt64> crateApiOpenLedgerSession({
    required String rootPath,
    required String entryFilePath,
  });

  Future<RustRefreshResult> crateApiRefreshLedgerSession({
    required PlatformInt64 handle,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCloseLedgerSession({required PlatformInt64 handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCloseLedgerSessionConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCloseLedgerSessionConstMeta => const TaskConstMeta(
    debugName: "close_ledger_session",
    argNames: ["handle"],
  );

  @override
  Future<RustAccountTree> crateApiGetAccountTree({
    required PlatformInt64 handle,
    required RustAccountTreeQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          sse_encode_box_autoadd_rust_account_tree_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_account_tree,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAccountTreeConstMeta,
        argValues: [handle, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAccountTreeConstMeta => const TaskConstMeta(
    debugName: "get_account_tree",
    argNames: ["handle", "query"],
  );

  @override
  Future<RustDocument> crateApiGetDocument({
    required PlatformInt64 handle,
    required String documentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          sse_encode_String(documentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_document,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetDocumentConstMeta,
        argValues: [handle, documentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDocumentConstMeta => const TaskConstMeta(
    debugName: "get_document",
    argNames: ["handle", "documentId"],
  );

  @override
  Future<RustJournalPage> crateApiGetJournalPage({
    required PlatformInt64 handle,
    required RustJournalQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          sse_encode_box_autoadd_rust_journal_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_journal_page,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetJournalPageConstMeta,
        argValues: [handle, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetJournalPageConstMeta => const TaskConstMeta(
    debugName: "get_journal_page",
    argNames: ["handle", "query"],
  );

  @override
  Future<RustLedgerSummary> crateApiGetLedgerSummary({
    required PlatformInt64 handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_ledger_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLedgerSummaryConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLedgerSummaryConstMeta => const TaskConstMeta(
    debugName: "get_ledger_summary",
    argNames: ["handle"],
  );

  @override
  Future<RustReportSnapshot> crateApiGetReportSnapshot({
    required PlatformInt64 handle,
    required RustReportQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          sse_encode_box_autoadd_rust_report_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_report_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetReportSnapshotConstMeta,
        argValues: [handle, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetReportSnapshotConstMeta => const TaskConstMeta(
    debugName: "get_report_snapshot",
    argNames: ["handle", "query"],
  );

  @override
  Future<List<RustLedgerDiagnostic>> crateApiListDiagnostics({
    required PlatformInt64 handle,
    required RustDiagnosticQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          sse_encode_box_autoadd_rust_diagnostic_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_ledger_diagnostic,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListDiagnosticsConstMeta,
        argValues: [handle, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListDiagnosticsConstMeta => const TaskConstMeta(
    debugName: "list_diagnostics",
    argNames: ["handle", "query"],
  );

  @override
  Future<List<RustDocumentSummary>> crateApiListDocuments({
    required PlatformInt64 handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_document_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListDocumentsConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListDocumentsConstMeta =>
      const TaskConstMeta(debugName: "list_documents", argNames: ["handle"]);

  @override
  Future<PlatformInt64> crateApiOpenLedgerSession({
    required String rootPath,
    required String entryFilePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_String(entryFilePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOpenLedgerSessionConstMeta,
        argValues: [rootPath, entryFilePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenLedgerSessionConstMeta => const TaskConstMeta(
    debugName: "open_ledger_session",
    argNames: ["rootPath", "entryFilePath"],
  );

  @override
  Future<RustRefreshResult> crateApiRefreshLedgerSession({
    required PlatformInt64 handle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_refresh_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRefreshLedgerSessionConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefreshLedgerSessionConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_ledger_session",
        argNames: ["handle"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RustAccountTreeQuery dco_decode_box_autoadd_rust_account_tree_query(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_account_tree_query(raw);
  }

  @protected
  RustAmount dco_decode_box_autoadd_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_amount(raw);
  }

  @protected
  RustDiagnosticQuery dco_decode_box_autoadd_rust_diagnostic_query(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_diagnostic_query(raw);
  }

  @protected
  RustJournalQuery dco_decode_box_autoadd_rust_journal_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_journal_query(raw);
  }

  @protected
  RustReportQuery dco_decode_box_autoadd_rust_report_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_report_query(raw);
  }

  @protected
  RustTransactionFlag dco_decode_box_autoadd_rust_transaction_flag(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_transaction_flag(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustAccountNode> dco_decode_list_rust_account_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_account_node).toList();
  }

  @protected
  List<RustDocumentSummary> dco_decode_list_rust_document_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_document_summary)
        .toList();
  }

  @protected
  List<RustJournalEntry> dco_decode_list_rust_journal_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_journal_entry).toList();
  }

  @protected
  List<RustLedgerDiagnostic> dco_decode_list_rust_ledger_diagnostic(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_ledger_diagnostic)
        .toList();
  }

  @protected
  List<RustReportResult> dco_decode_list_rust_report_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_report_result).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RustAmount? dco_decode_opt_box_autoadd_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rust_amount(raw);
  }

  @protected
  RustTransactionFlag? dco_decode_opt_box_autoadd_rust_transaction_flag(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_rust_transaction_flag(raw);
  }

  @protected
  RustAccountNode dco_decode_rust_account_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustAccountNode(
      name: dco_decode_String(arr[0]),
      subtitle: dco_decode_String(arr[1]),
      balance: dco_decode_String(arr[2]),
      isClosed: dco_decode_bool(arr[3]),
      isPostable: dco_decode_bool(arr[4]),
      children: dco_decode_list_rust_account_node(arr[5]),
    );
  }

  @protected
  RustAccountTree dco_decode_rust_account_tree(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RustAccountTree(nodes: dco_decode_list_rust_account_node(arr[0]));
  }

  @protected
  RustAccountTreeQuery dco_decode_rust_account_tree_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RustAccountTreeQuery(includeClosedAccounts: dco_decode_bool(arr[0]));
  }

  @protected
  RustAmount dco_decode_rust_amount(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustAmount(
      value: dco_decode_f_64(arr[0]),
      commodity: dco_decode_String(arr[1]),
      fractionDigits: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  RustDiagnosticQuery dco_decode_rust_diagnostic_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustDiagnosticQuery(
      includeBlocking: dco_decode_bool(arr[0]),
      includeNonBlocking: dco_decode_bool(arr[1]),
    );
  }

  @protected
  RustDocument dco_decode_rust_document(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustDocument(
      documentId: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      relativePath: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      sizeBytes: dco_decode_i_32(arr[4]),
      isEntry: dco_decode_bool(arr[5]),
    );
  }

  @protected
  RustDocumentSummary dco_decode_rust_document_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustDocumentSummary(
      documentId: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      relativePath: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_i_32(arr[3]),
      isEntry: dco_decode_bool(arr[4]),
    );
  }

  @protected
  RustJournalEntry dco_decode_rust_journal_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RustJournalEntry(
      dateIso8601: dco_decode_String(arr[0]),
      entryType: dco_decode_rust_journal_entry_type(arr[1]),
      title: dco_decode_String(arr[2]),
      primaryAccount: dco_decode_String(arr[3]),
      secondaryAccount: dco_decode_opt_String(arr[4]),
      detail: dco_decode_opt_String(arr[5]),
      amount: dco_decode_opt_box_autoadd_rust_amount(arr[6]),
      status: dco_decode_opt_String(arr[7]),
      transactionFlag: dco_decode_opt_box_autoadd_rust_transaction_flag(arr[8]),
    );
  }

  @protected
  RustJournalEntryType dco_decode_rust_journal_entry_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustJournalEntryType.values[raw as int];
  }

  @protected
  RustJournalPage dco_decode_rust_journal_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustJournalPage(
      totalCount: dco_decode_i_32(arr[0]),
      entries: dco_decode_list_rust_journal_entry(arr[1]),
    );
  }

  @protected
  RustJournalQuery dco_decode_rust_journal_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustJournalQuery(
      pageSize: dco_decode_i_32(arr[0]),
      offset: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  RustLedgerDiagnostic dco_decode_rust_ledger_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustLedgerDiagnostic(
      message: dco_decode_String(arr[0]),
      location: dco_decode_String(arr[1]),
      blocking: dco_decode_bool(arr[2]),
    );
  }

  @protected
  RustLedgerSummary dco_decode_rust_ledger_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return RustLedgerSummary(
      ledgerId: dco_decode_String(arr[0]),
      ledgerName: dco_decode_String(arr[1]),
      operatingCurrencies: dco_decode_list_String(arr[2]),
      loadedFileCount: dco_decode_i_32(arr[3]),
      openAccountCount: dco_decode_i_32(arr[4]),
      closedAccountCount: dco_decode_i_32(arr[5]),
      netWorth: dco_decode_String(arr[6]),
      totalAssets: dco_decode_String(arr[7]),
      totalLiabilities: dco_decode_String(arr[8]),
      changeDescription: dco_decode_String(arr[9]),
      weekTrend: dco_decode_rust_trend_summary(arr[10]),
      monthTrend: dco_decode_rust_trend_summary(arr[11]),
    );
  }

  @protected
  RustRefreshResult dco_decode_rust_refresh_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustRefreshResult(
      summary: dco_decode_rust_ledger_summary(arr[0]),
      diagnosticsCount: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  RustReportQuery dco_decode_rust_report_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return RustReportQuery();
  }

  @protected
  RustReportResult dco_decode_rust_report_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustReportResult(
      key: dco_decode_String(arr[0]),
      lines: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  RustReportSnapshot dco_decode_rust_report_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RustReportSnapshot(
      results: dco_decode_list_rust_report_result(arr[0]),
    );
  }

  @protected
  RustTransactionFlag dco_decode_rust_transaction_flag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustTransactionFlag.values[raw as int];
  }

  @protected
  RustTrendSummary dco_decode_rust_trend_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustTrendSummary(
      chartLabel: dco_decode_String(arr[0]),
      income: dco_decode_f_64(arr[1]),
      expense: dco_decode_f_64(arr[2]),
      balance: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RustAccountTreeQuery sse_decode_box_autoadd_rust_account_tree_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_account_tree_query(deserializer));
  }

  @protected
  RustAmount sse_decode_box_autoadd_rust_amount(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_amount(deserializer));
  }

  @protected
  RustDiagnosticQuery sse_decode_box_autoadd_rust_diagnostic_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_diagnostic_query(deserializer));
  }

  @protected
  RustJournalQuery sse_decode_box_autoadd_rust_journal_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_journal_query(deserializer));
  }

  @protected
  RustReportQuery sse_decode_box_autoadd_rust_report_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_report_query(deserializer));
  }

  @protected
  RustTransactionFlag sse_decode_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_transaction_flag(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustAccountNode> sse_decode_list_rust_account_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustAccountNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_account_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustDocumentSummary> sse_decode_list_rust_document_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustDocumentSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_document_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustJournalEntry> sse_decode_list_rust_journal_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustJournalEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_journal_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustLedgerDiagnostic> sse_decode_list_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustLedgerDiagnostic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_ledger_diagnostic(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustReportResult> sse_decode_list_rust_report_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustReportResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_report_result(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAmount? sse_decode_opt_box_autoadd_rust_amount(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_amount(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustTransactionFlag? sse_decode_opt_box_autoadd_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_transaction_flag(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAccountNode sse_decode_rust_account_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_String(deserializer);
    var var_balance = sse_decode_String(deserializer);
    var var_isClosed = sse_decode_bool(deserializer);
    var var_isPostable = sse_decode_bool(deserializer);
    var var_children = sse_decode_list_rust_account_node(deserializer);
    return RustAccountNode(
      name: var_name,
      subtitle: var_subtitle,
      balance: var_balance,
      isClosed: var_isClosed,
      isPostable: var_isPostable,
      children: var_children,
    );
  }

  @protected
  RustAccountTree sse_decode_rust_account_tree(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodes = sse_decode_list_rust_account_node(deserializer);
    return RustAccountTree(nodes: var_nodes);
  }

  @protected
  RustAccountTreeQuery sse_decode_rust_account_tree_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_includeClosedAccounts = sse_decode_bool(deserializer);
    return RustAccountTreeQuery(
      includeClosedAccounts: var_includeClosedAccounts,
    );
  }

  @protected
  RustAmount sse_decode_rust_amount(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_f_64(deserializer);
    var var_commodity = sse_decode_String(deserializer);
    var var_fractionDigits = sse_decode_i_32(deserializer);
    return RustAmount(
      value: var_value,
      commodity: var_commodity,
      fractionDigits: var_fractionDigits,
    );
  }

  @protected
  RustDiagnosticQuery sse_decode_rust_diagnostic_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_includeBlocking = sse_decode_bool(deserializer);
    var var_includeNonBlocking = sse_decode_bool(deserializer);
    return RustDiagnosticQuery(
      includeBlocking: var_includeBlocking,
      includeNonBlocking: var_includeNonBlocking,
    );
  }

  @protected
  RustDocument sse_decode_rust_document(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_documentId = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_relativePath = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_i_32(deserializer);
    var var_isEntry = sse_decode_bool(deserializer);
    return RustDocument(
      documentId: var_documentId,
      fileName: var_fileName,
      relativePath: var_relativePath,
      content: var_content,
      sizeBytes: var_sizeBytes,
      isEntry: var_isEntry,
    );
  }

  @protected
  RustDocumentSummary sse_decode_rust_document_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_documentId = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_relativePath = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_i_32(deserializer);
    var var_isEntry = sse_decode_bool(deserializer);
    return RustDocumentSummary(
      documentId: var_documentId,
      fileName: var_fileName,
      relativePath: var_relativePath,
      sizeBytes: var_sizeBytes,
      isEntry: var_isEntry,
    );
  }

  @protected
  RustJournalEntry sse_decode_rust_journal_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dateIso8601 = sse_decode_String(deserializer);
    var var_entryType = sse_decode_rust_journal_entry_type(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_primaryAccount = sse_decode_String(deserializer);
    var var_secondaryAccount = sse_decode_opt_String(deserializer);
    var var_detail = sse_decode_opt_String(deserializer);
    var var_amount = sse_decode_opt_box_autoadd_rust_amount(deserializer);
    var var_status = sse_decode_opt_String(deserializer);
    var var_transactionFlag = sse_decode_opt_box_autoadd_rust_transaction_flag(
      deserializer,
    );
    return RustJournalEntry(
      dateIso8601: var_dateIso8601,
      entryType: var_entryType,
      title: var_title,
      primaryAccount: var_primaryAccount,
      secondaryAccount: var_secondaryAccount,
      detail: var_detail,
      amount: var_amount,
      status: var_status,
      transactionFlag: var_transactionFlag,
    );
  }

  @protected
  RustJournalEntryType sse_decode_rust_journal_entry_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RustJournalEntryType.values[inner];
  }

  @protected
  RustJournalPage sse_decode_rust_journal_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalCount = sse_decode_i_32(deserializer);
    var var_entries = sse_decode_list_rust_journal_entry(deserializer);
    return RustJournalPage(totalCount: var_totalCount, entries: var_entries);
  }

  @protected
  RustJournalQuery sse_decode_rust_journal_query(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageSize = sse_decode_i_32(deserializer);
    var var_offset = sse_decode_i_32(deserializer);
    return RustJournalQuery(pageSize: var_pageSize, offset: var_offset);
  }

  @protected
  RustLedgerDiagnostic sse_decode_rust_ledger_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_blocking = sse_decode_bool(deserializer);
    return RustLedgerDiagnostic(
      message: var_message,
      location: var_location,
      blocking: var_blocking,
    );
  }

  @protected
  RustLedgerSummary sse_decode_rust_ledger_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ledgerId = sse_decode_String(deserializer);
    var var_ledgerName = sse_decode_String(deserializer);
    var var_operatingCurrencies = sse_decode_list_String(deserializer);
    var var_loadedFileCount = sse_decode_i_32(deserializer);
    var var_openAccountCount = sse_decode_i_32(deserializer);
    var var_closedAccountCount = sse_decode_i_32(deserializer);
    var var_netWorth = sse_decode_String(deserializer);
    var var_totalAssets = sse_decode_String(deserializer);
    var var_totalLiabilities = sse_decode_String(deserializer);
    var var_changeDescription = sse_decode_String(deserializer);
    var var_weekTrend = sse_decode_rust_trend_summary(deserializer);
    var var_monthTrend = sse_decode_rust_trend_summary(deserializer);
    return RustLedgerSummary(
      ledgerId: var_ledgerId,
      ledgerName: var_ledgerName,
      operatingCurrencies: var_operatingCurrencies,
      loadedFileCount: var_loadedFileCount,
      openAccountCount: var_openAccountCount,
      closedAccountCount: var_closedAccountCount,
      netWorth: var_netWorth,
      totalAssets: var_totalAssets,
      totalLiabilities: var_totalLiabilities,
      changeDescription: var_changeDescription,
      weekTrend: var_weekTrend,
      monthTrend: var_monthTrend,
    );
  }

  @protected
  RustRefreshResult sse_decode_rust_refresh_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_summary = sse_decode_rust_ledger_summary(deserializer);
    var var_diagnosticsCount = sse_decode_i_32(deserializer);
    return RustRefreshResult(
      summary: var_summary,
      diagnosticsCount: var_diagnosticsCount,
    );
  }

  @protected
  RustReportQuery sse_decode_rust_report_query(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustReportQuery();
  }

  @protected
  RustReportResult sse_decode_rust_report_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_String(deserializer);
    return RustReportResult(key: var_key, lines: var_lines);
  }

  @protected
  RustReportSnapshot sse_decode_rust_report_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_results = sse_decode_list_rust_report_result(deserializer);
    return RustReportSnapshot(results: var_results);
  }

  @protected
  RustTransactionFlag sse_decode_rust_transaction_flag(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RustTransactionFlag.values[inner];
  }

  @protected
  RustTrendSummary sse_decode_rust_trend_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chartLabel = sse_decode_String(deserializer);
    var var_income = sse_decode_f_64(deserializer);
    var var_expense = sse_decode_f_64(deserializer);
    var var_balance = sse_decode_f_64(deserializer);
    return RustTrendSummary(
      chartLabel: var_chartLabel,
      income: var_income,
      expense: var_expense,
      balance: var_balance,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_rust_account_tree_query(
    RustAccountTreeQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_account_tree_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_amount(
    RustAmount self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_amount(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_diagnostic_query(
    RustDiagnosticQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_diagnostic_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_journal_query(
    RustJournalQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_journal_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_report_query(
    RustReportQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_report_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_transaction_flag(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_account_node(
    List<RustAccountNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_account_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_document_summary(
    List<RustDocumentSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_document_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_journal_entry(
    List<RustJournalEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_journal_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_ledger_diagnostic(
    List<RustLedgerDiagnostic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_ledger_diagnostic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_report_result(
    List<RustReportResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_report_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_amount(
    RustAmount? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_amount(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_transaction_flag(
    RustTransactionFlag? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_transaction_flag(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_account_node(
    RustAccountNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.subtitle, serializer);
    sse_encode_String(self.balance, serializer);
    sse_encode_bool(self.isClosed, serializer);
    sse_encode_bool(self.isPostable, serializer);
    sse_encode_list_rust_account_node(self.children, serializer);
  }

  @protected
  void sse_encode_rust_account_tree(
    RustAccountTree self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_rust_account_node(self.nodes, serializer);
  }

  @protected
  void sse_encode_rust_account_tree_query(
    RustAccountTreeQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.includeClosedAccounts, serializer);
  }

  @protected
  void sse_encode_rust_amount(RustAmount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.value, serializer);
    sse_encode_String(self.commodity, serializer);
    sse_encode_i_32(self.fractionDigits, serializer);
  }

  @protected
  void sse_encode_rust_diagnostic_query(
    RustDiagnosticQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.includeBlocking, serializer);
    sse_encode_bool(self.includeNonBlocking, serializer);
  }

  @protected
  void sse_encode_rust_document(RustDocument self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.documentId, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.relativePath, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_32(self.sizeBytes, serializer);
    sse_encode_bool(self.isEntry, serializer);
  }

  @protected
  void sse_encode_rust_document_summary(
    RustDocumentSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.documentId, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.relativePath, serializer);
    sse_encode_i_32(self.sizeBytes, serializer);
    sse_encode_bool(self.isEntry, serializer);
  }

  @protected
  void sse_encode_rust_journal_entry(
    RustJournalEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dateIso8601, serializer);
    sse_encode_rust_journal_entry_type(self.entryType, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.primaryAccount, serializer);
    sse_encode_opt_String(self.secondaryAccount, serializer);
    sse_encode_opt_String(self.detail, serializer);
    sse_encode_opt_box_autoadd_rust_amount(self.amount, serializer);
    sse_encode_opt_String(self.status, serializer);
    sse_encode_opt_box_autoadd_rust_transaction_flag(
      self.transactionFlag,
      serializer,
    );
  }

  @protected
  void sse_encode_rust_journal_entry_type(
    RustJournalEntryType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_rust_journal_page(
    RustJournalPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.totalCount, serializer);
    sse_encode_list_rust_journal_entry(self.entries, serializer);
  }

  @protected
  void sse_encode_rust_journal_query(
    RustJournalQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.pageSize, serializer);
    sse_encode_i_32(self.offset, serializer);
  }

  @protected
  void sse_encode_rust_ledger_diagnostic(
    RustLedgerDiagnostic self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_bool(self.blocking, serializer);
  }

  @protected
  void sse_encode_rust_ledger_summary(
    RustLedgerSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ledgerId, serializer);
    sse_encode_String(self.ledgerName, serializer);
    sse_encode_list_String(self.operatingCurrencies, serializer);
    sse_encode_i_32(self.loadedFileCount, serializer);
    sse_encode_i_32(self.openAccountCount, serializer);
    sse_encode_i_32(self.closedAccountCount, serializer);
    sse_encode_String(self.netWorth, serializer);
    sse_encode_String(self.totalAssets, serializer);
    sse_encode_String(self.totalLiabilities, serializer);
    sse_encode_String(self.changeDescription, serializer);
    sse_encode_rust_trend_summary(self.weekTrend, serializer);
    sse_encode_rust_trend_summary(self.monthTrend, serializer);
  }

  @protected
  void sse_encode_rust_refresh_result(
    RustRefreshResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_ledger_summary(self.summary, serializer);
    sse_encode_i_32(self.diagnosticsCount, serializer);
  }

  @protected
  void sse_encode_rust_report_query(
    RustReportQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_rust_report_result(
    RustReportResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_list_String(self.lines, serializer);
  }

  @protected
  void sse_encode_rust_report_snapshot(
    RustReportSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_rust_report_result(self.results, serializer);
  }

  @protected
  void sse_encode_rust_transaction_flag(
    RustTransactionFlag self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_rust_trend_summary(
    RustTrendSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chartLabel, serializer);
    sse_encode_f_64(self.income, serializer);
    sse_encode_f_64(self.expense, serializer);
    sse_encode_f_64(self.balance, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
